fix some grammar mistakes and enhance Readme flow
ObaraEmmanuel/Formation pull request #16
Opened 2022-06-06 23:29 UTC by Mootbing

2022-06-07 18:32 UTC, ObaraEmmanuel requested changes
I really appreciate your effort in making this sound better. Aside from a few simple details looks okay and can be merged. Would you be interested in polishing the rest of the documentation?

2022-06-07 18:32 UTC, ObaraEmmanuel commented on README.md
> +After an installation, you can launch Formation Studio from the command line using the command
maybe remove the "an"

2022-06-07 18:32 UTC, ObaraEmmanuel commented on README.md
> +Formation Studio uses TKinter and, depending on the verion of Python installed, it may not be installed by default. If TKinter is not installed, install `tkinter` and `imagetk` after installing Forma
Should be "depending on the distribution/platform"

2022-06-07 18:32 UTC, ObaraEmmanuel commented on README.md
> +>possible issues in runtime.
should be "at runtime"

2022-06-07 18:32 UTC, ObaraEmmanuel commented on README.md
> +>Note: Its advisable that widget names are not named as reserved Python keywords to avoid
maybe remove the "named", seems redundant. Also, you need to mention something about being a valid python identifier. This allows us to cover other aspects such as the need to start with a letter or underscore, not having special characters and not being a reserved keyword.

2022-06-07 18:37 UTC, ObaraEmmanuel commented
> > 
> 
> of course! I want to help this open-source project as I really believe in it. I'll take a look at the other ones and make a PR for those too

Great. Are you familiar with making documentation with sphinx? Most of the documentation is done in sphinx and some of it is pulled directly from the code comments/docstrings.

2022-06-07 18:39 UTC, Mootbing commented
> 
> Great. Are you familiar with making documentation with sphinx? Most of the documentation is done in sphinx and some of it is pulled directly from the code comments/docstrings.

Imma be honest, I have no idea what Sphinx is, but if there is text within those files I can proofread those.

2022-06-07 18:55 UTC, Mootbing commented
I fixed the issues you've pointed out. I think it is possible now to merge.

2022-06-07 19:03 UTC, Mootbing commented
oh sorry, I just realized I sucked at GitHub and was supposed to approve changes instead of DIYing it. oops. Rest assured in the new commit the changes are there.

2022-06-07 21:10 UTC, ObaraEmmanuel commented on README.md
> +The underlying xml uses namespaces shown below:
"as shown".

2022-06-07 21:13 UTC, ObaraEmmanuel commented
> > Great. Are you familiar with making documentation with sphinx? Most of the documentation is done in sphinx and some of it is pulled directly from the code comments/docstrings.
> 
> Imma be honest, I have no idea what Sphinx is, but if there is text within those files I can proofread those.

It's basically just [reStructuredText](https://en.wikipedia.org/wiki/ReStructuredText) format instead of the usual markdown. Offers more features.

2022-06-07 22:12 UTC, Mootbing commented on README.md
> +The underlying xml uses namespaces shown below:
fixed

2022-06-07 22:12 UTC, Mootbing commented
alright ill check it out

2022-06-08 00:21 UTC, Mootbing commented
ok, there is a lot of documentation. I will probably run them over with Grammarly along with reading them myself. For now I think just merge the Readme.

2022-06-08 04:52 UTC, ObaraEmmanuel commented
LGTM, great work

2022-06-08 05:38 UTC, merged